### ISSUE TITLE
does the input require genomic or transcriptomic BAM from STAR

### ISSUE THREAD

**Issue by scseekers** [genemine/iread#5]
Hi 

I was going through your .md file wherein at the top, you have mentioned that transcript bam is required,
`a BAM file representing transcritome`

 but in the paper and as I read further in the .md file you mentioned the genomic BAM file
`the total number of mapped reads is 62000000 (reads mapped to the whole genome).`

Can you provide clarity on this  Also how do you define the total number of reads aligning to the genome? Unique + multi mapping reads obtained from STAR final.log.out file so the ones obtained from samtools flagstat. Also in your paper, you mentioned `fragments` which designate a pair of forward & reverse read. So should we consider the number of fragments or reads?

**Comment by genemine** [comment]
First, the total number of mapped reads is 62000000 as set by -t is only used to calculate FPKM. The reason I use this parameter is to make the FPKM value comparable to those calculated for gene expression. Taking using STAR as an example, STAR outputs the read count number for each gene in a given sample and assume that the sum of all genes' read counts is 30 million; in this case, you can set -t to 30million (library size) if you would like to compare intron expression to gene expression. You can also use 'samtools flagstat BAMFILE' to find the number of properly paired reads  (divided by 2 for paired end data) to feed to -t.

iREAD considers the number of fragments. For paired end RNA-seq, a pair of reads is considered as a fragment; for single end RNA-seq, a reads is considered as a fragment.

Thanks for your interest.
