### ISSUE TITLE
Array indices in assess_intron.py need to be shifted by 1

### ISSUE THREAD

**Issue by koustav-pal** [genemine/iread#6]
Hi, 

assess_intron.py processes the output from count_intronic_reads.pl which in turn reads in a bed file and makes the counts table. The file itself contains the entire line of the bed followed by a unique ID and then the counts. In a 0 based index system, the counts are present on column 7 and the IDs are present on column 6. Therefore, every column in the python script needs to be shifted by 1.

**Comment by genemine** [comment]
Hi @koustav-pal, thanks for your interest and comments. Yes, I checked again and the column ID is shifted by 1 in the python script. I will close this issue and please let me know if any further questions. Thank you.
